name: Add issues to project
on:
  workflow_call:
    secrets:
      TOOLKIT_PROJECT_PAT_CLASSIC:
        required: true
  issues:
    types: [opened, labeled, reopened] 

permissions:
  id-token: write
  contents: read
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@main
      with:
        project-url: https://github.com/orgs/web-illinois/projects/7
        github-token: ${{ secrets.TOOLKIT_PROJECT_PAT_CLASSIC }}
